### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by Mikiafk** [GeekyEggo/windows-display-settings#1]
when i use the resolution function to go to 1440x1080 it doesn't let me go back to 1920x1080 with another button setted

**Comment by GeekyEggo** [comment]
Hey @Mikiafk, just to confirm, is this 1440x1080, or 1440p?

**Comment by Mikiafk** [comment]
the resolution is 1440x1080 you can see it from the image in nvidia control panel
![immagine_2022-12-19_160240557](https://user-images.githubusercontent.com/98817587/208455433-65a069be-2c9c-4ed6-ba7d-b4f7b1266f75.png)

**Comment by GeekyEggo** [comment]
Is this resolution available as part of the display settings within Windows?
![image](https://user-images.githubusercontent.com/1429781/208457519-0e83d63a-f4ba-43ca-9bba-ff67dc167fc0.png)

**Comment by Mikiafk** [comment]
yes

**Comment by GeekyEggo** [comment]
Both 1920x1080 and 1440x1080 are listed in the built-in display settings in Windows (i.e. not NVIDIA)?

So I'm able to fully understand the replication steps, are you doing the following?

1. Action A has resolution 1920x1080
1. Action B has resolution 1440x1080
1. Press Action A, resolution updates
1. Press Action B, resolution does not change?

**Comment by Mikiafk** [comment]
invert action A and B in the 3 and 4

**Comment by Mikiafk** [comment]
hey, i still need help, just asking if you have another way to get it fixed?

**Comment by GeekyEggo** [comment]
Hey @Mikiafk, I'm unable to replicate the issue locally; could you provide a bit more detail into the exact replication steps please.

**Comment by Mikiafk** [comment]
https://user-images.githubusercontent.com/98817587/209191238-9c3944f1-c083-4f5a-a17d-ccbfc264b692.mp4

tell me if i explained it right

**Comment by GeekyEggo** [comment]
Thanks @Mikiafk, I really appreciate you going to the effort of creating a video to demonstrate the replication steps and the issue.

To help with investigating the issue further, I’m going to create a new beta build with more detailed logging; once this is ready, I’ll post a link here, and hopefully it will provide us with enough information to solve the problem. I’ll keep you posted.

**Comment by Mikiafk** [comment]
thank you for the help

**Comment by GeekyEggo** [comment]
Hey @Mikiafk, I've reviewed the code, and it looks as though we may be able to retrieve some logs from your recent issues. Within Windows Explorer, if you navigate to the folder; `%appdata%\elgato\StreamDeck\logs`, there will hopefully be some files named `com.geekyeggo.windowsdisplaysettings{number}.log`.

Could I ask you to add those files to this ticket, and I'll see if there's anything that might help us identify the root of the problem.

**Comment by Mikiafk** [comment]
unfortunately yesterday morning i did a reset to my pc and i didnt install stream deck yet, im very sorry i couldn't be helpfull

**Comment by GeekyEggo** [comment]
@Mikiafk that’s no problem at all; I’m going to temporarily close this ticket, but if you’re able to replicate the issue on a fresh install, please feel free to post the logs here, and I will re-open to continue the investigation. 😄
