### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by SirCadian** [GeekyEggo/windows-display-settings#10]
Just a suggestion for a (hopefully) small enhancement.  Could you Change the "Use HDR" function so that the icon changes based on the state of HDR (on or off)?  Just dimming the icon when off or having HDR with a slash through it would be great.  Thanks.

**Comment by GeekyEggo** [comment]
Hey @SirCadian, I have some good news, this is available as part of the [latest beta](https://github.com/GeekyEggo/windows-display-settings/raw/main/dist/com.geekyeggo.windowsdisplaysettings.streamDeckPlugin). 🙌 

As part of this beta, the HDR action is now a “multi-state” action that shows the current state of the HDR, and allows you to choose your preferred images for each state, i.e. on/off.

**Comment by SirCadian** [comment]
Amazing.  Thanks!
