### ISSUE TITLE
Changing resolution dosent work

### ISSUE THREAD

**Issue by DUBSDK** [GeekyEggo/windows-display-settings#14]
Hello i have an ultrawide monitor. On a daily basis i used WDS for rezizing down to 2560 x 1080 from 3840 x 1080. I worked and i loved it. I made blackbars on the sides so i could screenshare without problem. Not it dosent make the blackbars. All it does now is streatching my monitor out. Any fixes for this?

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀
