### ISSUE TITLE
Issue with stretch res

### ISSUE THREAD

**Issue by ArtanisCS** [GeekyEggo/windows-display-settings#17]
Going from Native (2560x1440) to 1600x1200 works fine, however when attempting to change back to Native it doesn't work, this issue only occurs when the scaling mode in Nvidia control panel is set to Full Screen rather than aspect ratio, however for stretched res I need it to be able to be set to Full-Screen, is there any possible fix for this?

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀
