### ISSUE TITLE
Can't raise after dropping resolution

### ISSUE THREAD

**Issue by TCNOco** [GeekyEggo/windows-display-settings#21]
This seems like great software to replace [Monitor Profile Switcher](https://sourceforge.net/projects/monitorswitcher/).
I set it to change my ultrawide to 16:9 for recording, and another button for back to 21:9.

When I change from 3440x1440 to 2560x1440 it works. When I press to change back to 3440x1440, it doesn't work. Whenever I try to move UP in resolution size it shows the yellow triangle and complains. I have no idea how to check logs for this, but I hope this is fixed as I REALLY want to have even less running on my system. This works well for lowering resolutions, but not for raising.

This seems similar to #18, if not the same, and even #8.

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀
