### ISSUE TITLE
Cannot change resolution to 1920x1080

### ISSUE THREAD

**Issue by VacrosDK** [GeekyEggo/windows-display-settings#22]
Whenever I switch to for example 1440x1080, it works perfectly, but the 1920x1080 does not work. It says the little yellow exclamation mark that indicates, something is wrong. Saw someone else with this problem, but that was a long time ago. :)

**Comment by deadlydog** [comment]
I too have this same issue

**Comment by tradaogit** [comment]
Tried this and work perfectly.

https://github.com/GeekyEggo/windows-display-settings/issues/8#issuecomment-1729052657

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀

**Comment by deadlydog** [comment]
I tested with the new version and still have this same issue, regardless of if I have the `Scaling Mode` set to `Default` or `Stretch`.
