### ISSUE TITLE
1600x900 does not fill the entire 16x9 monitor

### ISSUE THREAD

**Issue by deadlydog** [GeekyEggo/windows-display-settings#23]
When using this to switch a monitor to 1600x900 resolution, there is a black horizontal bar across the top and bottom of the monitor, even though the monitor is a 16x9 monitor. So the screen does not fill the entire monitor, and the contents get stretched/skewed a bit. If I use the Windows Display Settings to set the monitor to 1600x900 then it fills the entire monitor as expected. Other 16x9 resolutions seem to work fine (1920x1080 and 1280x720); only 1600x900 has this problem where it does not fill the entire space, and ends up with a resolution closer to 20x9.

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀

**Comment by deadlydog** [comment]
Setting the scaling mode to `Stretch` resolves this issue. Thanks!
