### ISSUE TITLE
Feature Request: Toggle Resolution

### ISSUE THREAD

**Issue by nr4z** [GeekyEggo/windows-display-settings#27]
Hey - Thank you for your awsome work at first!
It would be nice if you can also toggle the resolution. 
I think, most time you change the resolution of your monitor, you also want to change it back. 
It's also really nice to switch from ultrawinde 32:9 to 16:9 for some speacial cases.

**Comment by GeekyEggo** [comment]
Hi @nr4z, the "Multi Action Switch" action (built into Stream Deck app) can help here — with this action, you can build two multi-actions that toggle on press, and should provide the desired functionality. 😄
