### ISSUE TITLE
resolution problem

### ISSUE THREAD

**Issue by mkterius** [GeekyEggo/windows-display-settings#3]
https://github.com/GeekyEggo/windows-display-settings/issues/1#issuecomment-1363139227
exact same problem happened to me

this is the log file
[com.geekyeggo.windowsdisplaysettings0.log](https://github.com/GeekyEggo/windows-display-settings/files/10688334/com.geekyeggo.windowsdisplaysettings0.log)

The problem occurs only when changing to 1920x1080 resolution.

**Comment by GeekyEggo** [comment]
Hey @mkterius, thanks for attaching the logs; having reviewed them, this appears to be due to invalid settings when attempting to update the monitor config (not your fault). When I'm able to find time, I'm going to investigate a little further to see if I can clean up the underlying implementation that should hopefully resolve this.

**Comment by mkterius** [comment]
@GeekyEggo There is one more thing I had found. This problem occurs on monitors using DP port. There is no problem with the same monitor using the HDMI port.

**Comment by GeekyEggo** [comment]
oh, that's interesting! Another user reported problems with resolutions in ultrawide monitors too (#5). With all of the problems surrounding resolutions, I'm unhappy with how the action is currently implemented. My intention is to re-write it over the coming weeks in an effort to make it more robust.

**Comment by mkterius** [comment]
@GeekyEggo I solved this problem by removing the 1920x1080 of the TV resolutions displayed in the Nvidia Control Panel using  CRU.
![image](https://user-images.githubusercontent.com/123555069/221633252-5e94c220-bb12-4a92-b676-1fbb584d8855.png)

https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU

**Comment by GeekyEggo** [comment]
Hey @mkterius, this is great news; is the problem completely resolved for you now? 😄

**Comment by mkterius** [comment]
For now, yes. however, It's hard to satisfied with having to rely on other utilities

**Comment by GrayWolf8856** [comment]
Sadly I’m still having the issue

**Comment by SazinhoTweaks** [comment]
Update here: Still happens on DP output, tried to delete all TV resolutions from LG OLED monitor and they won't go away, some locked settings about it. @GeekyEggo any update on a fix? can change res to 1920x1080 but going back to 2560x1440 won't work.

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀
