### ISSUE TITLE
Windows 11: Changing to lower resolution stretches the display instead of centering it on ultrawide 

### ISSUE THREAD

**Issue by khdc** [GeekyEggo/windows-display-settings#5]
I have an ultrawide display and recently switched to Windows 11. When I resize down to 1920x1080, the screen is stretched instead of being centered on the display.

**Comment by GeekyEggo** [comment]
Hey @khdc, although I don’t own an ultrawide, a close friends does - I’ll need to gather some analytics from them first before I’m able to resolve this successfully, but I’ll see what I can do. 🤞 Thanks for bringing it to my attention,

**Comment by PetrVobornik** [comment]
It is necessary to change [this](https://github.com/GeekyEggo/windows-display-settings/blob/0fc575baeb10f9b6527a68fe777795db428df6ab/src/Extensions/DisplayExtensions.cs#L94C37-L94C37) from "settings.OutputScalingMode" to this "DisplayFixedOutput.Center", or add it as another parameter for the selection.

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀
