### ISSUE TITLE
Enhancement - Monitor Extension Settings

### ISSUE THREAD

**Issue by Paladinleeds** [GeekyEggo/windows-display-settings#7]
Would be nice to be able to set if a monitor will extend itself or will duplicate off another monitor. I use an ATEM so would need a way to duplicate my main monitor to the HDMI out that leads to the ATEM switcher.

**Comment by GeekyEggo** [comment]
Hey @Paladinleeds, if I'm understanding correctly, this might be achievable if #4 were implemented, in conjunction with the existing "Project" action?

![image](https://user-images.githubusercontent.com/1429781/232795732-b9f64483-4e27-4009-9f94-f0194e2bdc5d.png)

**Comment by Paladinleeds** [comment]
@GeekyEggo this looks brilliant. Be sure to add an option for duplicate to select which monitor to duplicate. And for the extend option, I would say two options, one to select a reference monitor and a second to select if it goes to the left, right, above, or below the reference monitor.

**Comment by GeekyEggo** [comment]
@Paladinleeds I'd like that too, however sadly that isn't how Windows handles projecting. The "Duplicate", and "Extend" options are only able to extend the primary monitor.
