### ISSUE TITLE
 native 1920x1080 resolution doesnt work

### ISSUE THREAD

**Issue by middag123** [GeekyEggo/windows-display-settings#8]
I use 1680x1080 and 1440x1080, they work but it doesnt work to go back to 1920x1080(native)

**Comment by HBerthol** [comment]
Same for me : i use 1920x1080, 2560x1080, they work but can't go back to 3840x1080 (native)

**Comment by lyndonguitar** [comment]
> Same for me : i use 1920x1080, 2560x1080, they work but can't go back to 3840x1080 (native)

it was perfectly fine until I changed my displayport cable. which is super weird

**Comment by lyndonguitar** [comment]
> Same for me : i use 1920x1080, 2560x1080, they work but can't go back to 3840x1080 (native)

okay I found the fix. Install CRU and then reset all settings

**Comment by HBerthol** [comment]
> > Same for me : i use 1920x1080, 2560x1080, they work but can't go back to 3840x1080 (native)
> 
> okay I found the fix. Install CRU and then reset all settings

How do you do this ?

**Comment by HBerthol** [comment]
It works like a charm : just launch "reset-all.exe" from cr v1.5.2, reboot and that's it ! 
Thank you @lyndonguitar !

**Comment by Siaomo** [comment]
> > 對我來說也是如此：我使用 1920x1080、2560x1080，它們可以工作，但無法返回到 3840x1080（原生）
> 
> 好吧，我找到了修復方法。安裝 CRU，然後重置所有設置

can i ask what is cru because i have same problem change1280*960 OK changeback to1920*1080 not work

**Comment by HBerthol** [comment]
> > > 對我來說也是如此：我使用 1920x1080、2560x1080，它們可以工作，但無法返回到 3840x1080（原生）
> > 
> > 
> > 好吧，我找到了修復方法。安裝 CRU，然後重置所有設置
> 
> can i ask what is cru because i have same problem change1280_960 OK changeback to1920_1080 not work

CRU for Custom Resolution Utility
You can find it here : https://monitortests.com/custom-resolution-utility

**Comment by Siaomo** [comment]
> > > > 對我來說也是如此：我使用1920x1080、2560x1080，它們可以工作，但無法返回3840x1080（實際上）
> > > 
> > > 
> > > 好吧，我找到了修復方法。安裝CRU，然後重置所有設置
> > 
> > 
> > 我可以問什麼是 cru 因為我有同樣的問題change1280_960 OK 改回1920_1080 不起作用
> 
> 用於自訂解析度實用程式的 CRU 您可以在這裡找到它：https://monitortests.com/custom-resolution-utility

ok thanks I'll try to see how it works because English is not my native language so it's a bit tricky.

**Comment by jefferai** [comment]
CRU didn't help for me. The issue (for me) seems to be changing back to native resolution if I have GPU-based scaling (instead of display-based scaling) selected in NVCP. If it's set to GPU-based scaling when I press the button there is a yellow triangle that appears and nothing happens. If it's set to display-based scaling it works fine (but then it's not the behavior I want from the lower resolutions).

**Comment by HBerthol** [comment]
QRes.exe is the only solution I have found and it is working fine with Advanced Launcher (ie. with theses arguments : "/x:1920 /y:1080" or "/x:2560 /y:1080" or "/x:3840 /y:1080"

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀

**Comment by HBerthol** [comment]
Thanks Richard,

It works with these parameters :

1920x1080 “Center”
2560x1080 “Center”
3840x1080 “Default” (NB : “Center” does not work)

Regards
