### ISSUE TITLE
Displays does not load after reboot and resolution change wont execute 

### ISSUE THREAD

**Issue by thefctnwelive** [GeekyEggo/windows-display-settings#9]
When I first install the plugin and create a "Resolution" button both of my displays will show from the "Display" drop list. When I use the buton to change the resolution on my main display to 1920x1080 it work as expected. 

Upon reboot of the machine non of the Resolution change button will not work unless I uninstall and reinstall the plug in. 

I go back into streamdeck and the "Display" drop down will only show "Loading..." 

If I uninstall the plug in and reinstall the "Displays" will once again show and I am able to use the button once. 

I am also getting a similar result by setting up a button successfully and simply copy and past the button to make a new resolution the same thing will happen. The "Display" drop list for both old and new button will be stuck on "Loading..." and neither will work.

If I close and open the Stream Deck software I am able to once again able to select a display and the buttons work as expected. 

But any reboot of the machine and its back to square 1 of re-install 

Please let me know if there is any additional information I can provide.

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀
